spring.application.name=smartbox-backend
#spring.data.mongodb.uri=mongodb+srv://smartboxadmin:smartbox123@smartbox-cluster.g9hpsvr.mongodb.net/smartbox?retryWrites=true&w=majority&appName=smartbox-cluster
spring.data.mongodb.uri=mongodb://localhost:27017/smartbox
